Warning -Duplicate keyword: SECTION input with ID=1 
  Warning occurs in file F:\SafetyMunition\SafetyMunitionTestPlatform\Fragment_ignition_control.k
Last one will be used
Warning -Duplicate keyword: SECTION input with ID=2 
  Warning occurs in file F:\SafetyMunition\SafetyMunitionTestPlatform\Fragment_ignition_control.k
Last one will be used
Warning - EOS 1 not found:
  Referenced in *PART ID = 1
Warning - EOS 2 not found:
  Referenced in *PART ID = 2
Warning - DEFINE_CURVE 2 not found:
  Referenced in *MAT_ADD_EROSION ID = 1
Warning - DEFINE_CURVE 1 not found:
  Referenced in *MAT_ADD_EROSION ID = 2
Warning - DEFINE_CURVE 2 not found:
  Referenced in *MAT_ADD_EROSION ID = 2
Message 0
