#include "LSDynaDeck.h"
#include <fstream>
#include <iostream>

void LSDynaDeck::addCard(std::shared_ptr<KeywordCard> card) {
    deck.push_back(card);
}

void LSDynaDeck::setMeshInclude(const std::string& path) {
    meshIncludePath = path;
}

void LSDynaDeck::writeToFile(const std::string& filename) {
    std::ofstream out(filename);
    if (!out.is_open()) {
        std::cerr << "无法打开文件进行写入: " << filename << "\n";
        return;
    }

    out << "*KEYWORD MEMORY=399999999\n";
    out << "*TITLE\nFragment_ignition_AutoGenerated\n";

    for (const auto& card : deck) {
        out << card->generate();
    }

    if (!meshIncludePath.empty()) {
        out << "*INCLUDE\n";
        out << meshIncludePath << "\n";
    }

    out << "*END\n";
    out.close();
    std::cout << "K文件成功生成: " << filename << "\n";
}